// Code generated by protoc-gen-go.
// source: orchestra.proto
// DO NOT EDIT!

/*
Package orchestra is a generated protocol buffer package.

It is generated from these files:
	orchestra.proto

It has these top-level messages:
	IdentifyClient
	ProtoJobParameter
	ProtoTaskRequest
	ProtoAcknowledgement
	ProtoTaskResponse
*/
package orchestra

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ProtoAcknowledgement_AckType int32

const (
	ProtoAcknowledgement_ACK_OK    ProtoAcknowledgement_AckType = 1
	ProtoAcknowledgement_ACK_ERROR ProtoAcknowledgement_AckType = 3
)

var ProtoAcknowledgement_AckType_name = map[int32]string{
	1: "ACK_OK",
	3: "ACK_ERROR",
}
var ProtoAcknowledgement_AckType_value = map[string]int32{
	"ACK_OK":    1,
	"ACK_ERROR": 3,
}

func (x ProtoAcknowledgement_AckType) Enum() *ProtoAcknowledgement_AckType {
	p := new(ProtoAcknowledgement_AckType)
	*p = x
	return p
}
func (x ProtoAcknowledgement_AckType) String() string {
	return proto.EnumName(ProtoAcknowledgement_AckType_name, int32(x))
}
func (x *ProtoAcknowledgement_AckType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProtoAcknowledgement_AckType_value, data, "ProtoAcknowledgement_AckType")
	if err != nil {
		return err
	}
	*x = ProtoAcknowledgement_AckType(value)
	return nil
}

type ProtoTaskResponse_TaskStatus int32

const (
	ProtoTaskResponse_JOB_INPROGRESS      ProtoTaskResponse_TaskStatus = 2
	ProtoTaskResponse_JOB_SUCCESS         ProtoTaskResponse_TaskStatus = 3
	ProtoTaskResponse_JOB_FAILED          ProtoTaskResponse_TaskStatus = 4
	ProtoTaskResponse_JOB_HOST_FAILURE    ProtoTaskResponse_TaskStatus = 5
	ProtoTaskResponse_JOB_UNKNOWN         ProtoTaskResponse_TaskStatus = 6
	ProtoTaskResponse_JOB_UNKNOWN_FAILURE ProtoTaskResponse_TaskStatus = 7
)

var ProtoTaskResponse_TaskStatus_name = map[int32]string{
	2: "JOB_INPROGRESS",
	3: "JOB_SUCCESS",
	4: "JOB_FAILED",
	5: "JOB_HOST_FAILURE",
	6: "JOB_UNKNOWN",
	7: "JOB_UNKNOWN_FAILURE",
}
var ProtoTaskResponse_TaskStatus_value = map[string]int32{
	"JOB_INPROGRESS":      2,
	"JOB_SUCCESS":         3,
	"JOB_FAILED":          4,
	"JOB_HOST_FAILURE":    5,
	"JOB_UNKNOWN":         6,
	"JOB_UNKNOWN_FAILURE": 7,
}

func (x ProtoTaskResponse_TaskStatus) Enum() *ProtoTaskResponse_TaskStatus {
	p := new(ProtoTaskResponse_TaskStatus)
	*p = x
	return p
}
func (x ProtoTaskResponse_TaskStatus) String() string {
	return proto.EnumName(ProtoTaskResponse_TaskStatus_name, int32(x))
}
func (x *ProtoTaskResponse_TaskStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProtoTaskResponse_TaskStatus_value, data, "ProtoTaskResponse_TaskStatus")
	if err != nil {
		return err
	}
	*x = ProtoTaskResponse_TaskStatus(value)
	return nil
}

// P->C : Provide Client Identity and negotiate other initial parameters
type IdentifyClient struct {
	Hostname         *string `protobuf:"bytes,1,req,name=hostname" json:"hostname,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IdentifyClient) Reset()         { *m = IdentifyClient{} }
func (m *IdentifyClient) String() string { return proto.CompactTextString(m) }
func (*IdentifyClient) ProtoMessage()    {}

func (m *IdentifyClient) GetHostname() string {
	if m != nil && m.Hostname != nil {
		return *m.Hostname
	}
	return ""
}

type ProtoJobParameter struct {
	Key              *string `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            *string `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoJobParameter) Reset()         { *m = ProtoJobParameter{} }
func (m *ProtoJobParameter) String() string { return proto.CompactTextString(m) }
func (*ProtoJobParameter) ProtoMessage()    {}

func (m *ProtoJobParameter) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *ProtoJobParameter) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

// C->P : Do Shit kthxbye
type ProtoTaskRequest struct {
	Jobname          *string              `protobuf:"bytes,1,req,name=jobname" json:"jobname,omitempty"`
	Id               *uint64              `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Parameters       []*ProtoJobParameter `protobuf:"bytes,3,rep,name=parameters" json:"parameters,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *ProtoTaskRequest) Reset()         { *m = ProtoTaskRequest{} }
func (m *ProtoTaskRequest) String() string { return proto.CompactTextString(m) }
func (*ProtoTaskRequest) ProtoMessage()    {}

func (m *ProtoTaskRequest) GetJobname() string {
	if m != nil && m.Jobname != nil {
		return *m.Jobname
	}
	return ""
}

func (m *ProtoTaskRequest) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ProtoTaskRequest) GetParameters() []*ProtoJobParameter {
	if m != nil {
		return m.Parameters
	}
	return nil
}

// C->P, P->C : Acknowledge Message
type ProtoAcknowledgement struct {
	Id               *uint64                       `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Response         *ProtoAcknowledgement_AckType `protobuf:"varint,2,req,name=response,enum=orchestra.ProtoAcknowledgement_AckType,def=1" json:"response,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *ProtoAcknowledgement) Reset()         { *m = ProtoAcknowledgement{} }
func (m *ProtoAcknowledgement) String() string { return proto.CompactTextString(m) }
func (*ProtoAcknowledgement) ProtoMessage()    {}

const Default_ProtoAcknowledgement_Response ProtoAcknowledgement_AckType = ProtoAcknowledgement_ACK_OK

func (m *ProtoAcknowledgement) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ProtoAcknowledgement) GetResponse() ProtoAcknowledgement_AckType {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return Default_ProtoAcknowledgement_Response
}

// P->C : Results from Task
type ProtoTaskResponse struct {
	Id               *uint64                       `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Status           *ProtoTaskResponse_TaskStatus `protobuf:"varint,3,req,name=status,enum=orchestra.ProtoTaskResponse_TaskStatus" json:"status,omitempty"`
	Response         []*ProtoJobParameter          `protobuf:"bytes,4,rep,name=response" json:"response,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *ProtoTaskResponse) Reset()         { *m = ProtoTaskResponse{} }
func (m *ProtoTaskResponse) String() string { return proto.CompactTextString(m) }
func (*ProtoTaskResponse) ProtoMessage()    {}

func (m *ProtoTaskResponse) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ProtoTaskResponse) GetStatus() ProtoTaskResponse_TaskStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ProtoTaskResponse_JOB_INPROGRESS
}

func (m *ProtoTaskResponse) GetResponse() []*ProtoJobParameter {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterEnum("orchestra.ProtoAcknowledgement_AckType", ProtoAcknowledgement_AckType_name, ProtoAcknowledgement_AckType_value)
	proto.RegisterEnum("orchestra.ProtoTaskResponse_TaskStatus", ProtoTaskResponse_TaskStatus_name, ProtoTaskResponse_TaskStatus_value)
}
